apiVersion: v1
kind: Service
metadata:
  name: playground-kustomize
  labels:
    app: playground-kustomize
spec:
  selector:
    app: playground-kustomize
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080